### ISSUE TITLE
order toc alphabetically

### ISSUE THREAD

**Issue by cyberthal** [uvtc/rippledoc#5]
I would like the automatically-generated table of contents to be ordered alphabetically.  

That way I can simply number the files and directories in the desired order on my file system, and have that order reflected on the site.

Currently the order deviates from alphabetical in strange ways.

EDIT:  This behavior appeared when building on nearlyfreespeech.net's server, but not when building on my Mac.  So far so good.

**Comment by uvtc** [comment]
Ah. Thanks for pointing this out. Yes, at the moment there's no defined ordering for the default toc's. I'd assumed that authors would much prefer to do the ordering in the toc.conf file(s), rather than name/rename their files with leading zero-padded numbers to get the ordering they want.

That said, I'll change it this week to sort the default toc's.

Incidentally, you can always create our own toc.conf file in a given directory, with asciibetically-sorted entries by doing something like: `ls -1 *.md > toc.conf` then manually add in the dir names.

**Comment by leobuchignani** [comment]
I'm delighted to hear the change is coming so soon!  Your tool is already fantastic in concept and execution - tight feedback loop, low config friction.  

I use entr, shell scripts, a Rakefile and live-reload to display Rippledoc in a browser as I write.  This addition will allow me to refactor markdown files and directories in Emacs dired, and have those changes automatically update in my browser.  I believe it completes the tool's affordance.

When writing an expanding text base with complex interrelationships, the optimal reading order and the best-fit folder categorization evolve unpredictably.  Individual markdown files undergo a lifecycle of multiple growths, name changes and splits.  Config-less sequencing permits Rippledoc to be adopted earlier in the writing process, before the final order is known.  This frees brainpower and conscientiousness the author would otherwise have devoted to ToC maintenance and state.  His directory tree is WYSIWYG.  There is no dislocation between browsing the file system and the html nav tree.  The feedback loop is closed.  

The point of the change is not to obsessively renumber all one's files.  Rather, it's to allow a hybrid state with ordered and unordered elements coexisting peacefully.  For some items the order doesn't matter, and then it's a pain to maintain a numerical sequence.  For other items the order matters greatly, and it's a pain to view the jumbled sequence.

I've reviewed a significant subset of static site generators and AFAICT there's nothing else that can do this past 3-4 directories of depth and still maintain a usable UI.  

Rippledoc's UI is scale resistant if not impervious, but its build speed is merely average and might become unwieldy at scale.  A build tool would certainly help - there are many superfluous file system writes.  Off the top of your head, do you think the CPU bottleneck would benefit from consumer-accessible cloud parallelization?  If so then I don't see a practical limit to document repository size for an individual user.

**Comment by uvtc** [comment]
Ok. Entries in the default toc.conf files start out sorted. Updated version to v0.1.2.

**Comment by uvtc** [comment]
> there are many superfluous file system writes.

Yes. I need to think more about to handle that.

> Off the top of your head, do you think the CPU bottleneck would benefit from consumer-accessible cloud parallelization?

Rippledoc is not optimized --- it's just a simple doc processor that kicks off pandoc multiple times to do the hard work. Haven't thought about parallelization.

**Comment by cyberthal** [comment]
To solve superfluous FS rewrites, some suggestions: 

write the output to memory:
http://askubuntu.com/questions/548661/how-can-i-run-a-bash-script-without-affecting-the-file-system

then rsync it to the target directory
https://www.npmjs.com/package/gulp-rsync/

Here are some primitive shell scripts I wrote to clean, build and watch Rippledoc
https://github.com/cyberthal/ripplewrap

**Comment by uvtc** [comment]
Neat. Thanks for the links.
